// flow-typed signature: a54bab25af12eafcdb3b5a0426ecb7b9
// flow-typed version: <<STUB>>/@types/react-native_v^0.48.6/flow_v0.49.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-native' {
  declare module.exports: any;
}
